// Code generated by nofaultctl from /Users/Wang/Code/webfault-lib2/nofault-all/nofault/examples/v0.5.0-data-user-api/api/user.api.ts. DO NOT EDIT.
import { IsEmail, IsInt, IsOptional, IsString, MaxLength, Min, MinLength } from '@nofault/rest';
export class CreateUserReq {
  @IsString()