// Code generated by nofaultctl from /Users/Wang/Code/webfault-lib2/nofault-all/nofault/examples/v0.5.0-data-user-api/api/user.api.ts. DO NOT EDIT.
import { IsInt, Min } from '@nofault/rest';
export class ListUsersReq {
  @IsInt()
  @Min(1)
  page!: number;
  @IsInt()
  @Min(1)
  pageSize!: number;