/**
 * `nofaultctl new <project>` —— 脚手架。
 *
 * 目标很具体：脚手架生成的工程**立刻能跑**，而不是留一堆 TODO 让用户自己填。
 * 所以这里会：
 * 1. 写出工程骨架（package.json / tsconfig / main.ts / app.module.ts）
 * 2. 写出一份示例契约 `api/<name>.api.ts`
 * 3. **立刻按契约生成一遍代码** —— 用户 `npm i && npm start` 就能 curl
 */

import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pascalCase, kebabCase } from '@nofault/dsl';
import { log } from '../log';

export interface NewOptions {
  /** 目标目录（默认等于项目名） */
  dir?: string;
  /** 是否跳过契约驱动的首次生成 */
  skipGenerate?: boolean;
}

export interface NewResult {
  dir: string;
  files: string[];
}

export function scaffold(name: string, options: NewOptions = {}): NewResult {
  const dir = resolve(options.dir ?? name);
  if (existsSync(dir) && readdirSync(dir).length > 0) {
    // 非空目录直接失败：脚手架覆盖用户代码是不可接受的。
    // 空目录放行 —— `mkdir deps && cd deps && nofaultctl new x` 是很自然的用法。
    throw new Error(`directory already exists and is not empty: ${dir}`);
  }

  const files: string[] = [];
  const emit = (rel: string, content: string): void => {
    const abs = join(dir, rel);
    mkdirSync(pathDir(abs), { recursive: true });
    writeFileSync(abs, content, 'utf8');
    files.push(rel);
  };

  emit('package.json', packageJson(name));
  emit('tsconfig.json', tsconfig());
  emit('.gitignore', gitignore());
  emit('README.md', readme(name));
  emit('src/main.ts', mainTs(name));
  emit('src/app.module.ts', appModuleTs());
  emit(`api/${kebabCase(name)}.api.ts`, contractTs(name));

  log.step(`scaffolded ${files.length} file(s) into ${dir}`);
  return { dir, files };
}

function pathDir(abs: string): string {
  const i = abs.lastIndexOf('/');
  return i < 0 ? abs : abs.slice(0, i);
}

// --------------------------------------------------------------------- 模板

function packageJson(name: string): string {
  return `${JSON.stringify(
    {
      name: kebabCase(name),
      version: '0.1.0',
      private: true,
      description: `Generated by nofaultctl · ${new Date().toISOString().slice(0, 10)}`,
      scripts: {
        build: 'tsc -p tsconfig.json',
        start: 'node dist/main.js',
        dev: 'tsc -p tsconfig.json && node dist/main.js',
        generate: `nofaultctl generate api api/${kebabCase(name)}.api.ts --out src`,
      },
      dependencies: {
        '@nofault/core': '^0.4.0',
        '@nofault/rest': '^0.4.0',
        '@nofault/logger': '^0.4.0',
        'reflect-metadata': '^0.2.2',
      },
      devDependencies: {
        '@nofault/cli': '^0.4.0',
        typescript: '^5.6.0',
      },
    },
    null,
    2,
  )}\n`;
}

function tsconfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'commonjs',
        moduleResolution: 'node',
        experimentalDecorators: true,
        emitDecoratorMetadata: true,
        strict: true,
        skipLibCheck: true,
        esModuleInterop: true,
        declaration: false,
        outDir: 'dist',
        rootDir: 'src',
      },
      include: ['src/**/*.ts'],
    },
    null,
    2,
  )}\n`;
}

function gitignore(): string {
  return ['node_modules/', 'dist/', 'logs/', ''].join('\n');
}

function readme(name: string): string {
  const kebab = kebabCase(name);
  // 说明文字里刻意不出现反引号：这是模板字符串，反引号会提前结束字符串
  return `# ${pascalCase(name)}

Generated by \`nofaultctl new ${name}\`.

\`\`\`bash
npm install
npm run dev          # 编译并启动
curl -s http://127.0.0.1:3000/${kebab}/ping
\`\`\`

## 目录

\`\`\`
api/${kebab}.api.ts      契约：改这里，然后 npm run generate
src/${kebab}/            生成产物（controller / service / module）
src/dto/                 生成的 DTO
src/app.module.ts        根模块（生成）
src/main.ts              启动入口（脚手架生成，可自由修改）
\`\`\`

> src/main.ts 不在生成器的管理范围，可以自由修改。
> 其余文件默认是**只覆盖生成器自己写过的**（靠首行生成标记识别），手工改过的会被跳过。
`;
}

function mainTs(name: string): string {
  return `import 'reflect-metadata';
import { createLogger } from '@nofault/logger';
import { RestApplication, bodyParser, cors, requestContext, securityHeaders } from '@nofault/rest';
import { AppModule } from './app.module';

const logger = createLogger({ context: '${kebabCase(name)}' });

async function bootstrap(): Promise<void> {
  const app = await RestApplication.create(AppModule, {
    name: '${kebabCase(name)}',
    logger,
    middleware: [requestContext(), cors(), securityHeaders(), bodyParser()],
  });

  app.enableShutdownHooks();
  const port = Number(process.env.PORT ?? 3000);
  const { port: actualPort } = await app.listen(port);
  app.markReady();

  logger.info('ready', { port: actualPort });
  for (const route of app.getRoutes()) {
    logger.info(\`  \${route.method.padEnd(6)} \${route.path}\`);
  }
}

void bootstrap().catch((err: unknown) => {
  logger.error('bootstrap failed', undefined, err);
  if (err instanceof Error && err.stack) process.stderr.write(\`\${err.stack}\\n\`);
  process.exit(1);
});
`;
}

function appModuleTs(): string {
  return `// Code generated by nofaultctl. DO NOT EDIT.
import { Module } from '@nofault/core';

@Module({})
export class AppModule {}
`;
}

function contractTs(name: string): string {
  const kebab = kebabCase(name);
  return `/**
 * ${pascalCase(name)} 的 API 契约。
 *
 * 改完跑：\`npm run generate\`
 */
import {
  Api, Prefix, Get, Post, Handler,
  Body, Query, IsString, IsInt, IsNotEmpty, MinLength, MaxLength, IsOptional,
} from '@nofault/dsl';

export class PingResp {
  @Body('message') @IsString() @IsNotEmpty()
  message!: string;
}