/**
 * `nofaultctl new <project>` —— 脚手架。
 *
 * 目标很具体：脚手架生成的工程**立刻能跑**，而不是留一堆 TODO 让用户自己填。
 * 所以这里会：
 * 1. 写出工程骨架（package.json / tsconfig / main.ts / app.module.ts）
 * 2. 写出一份示例契约 `api/<name>.api.ts`
 * 3. **立刻按契约生成一遍代码** —— 用户 `npm i && npm start` 就能 curl
 */

import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pascalCase, kebabCase } from '@nofault/dsl';
import { log } from '../log';

export interface NewOptions {
  /** 目标目录（默认等于项目名） */
  dir?: string;
  /** 是否跳过契约驱动的首次生成 */
  skipGenerate?: boolean;
}

export interface NewResult {
  dir: string;
  files: string[];
}

export function scaffold(name: string, options: NewOptions = {}): NewResult {
  const dir = resolve(options.dir ?? name);
  if (existsSync(dir) && readdirSync(dir).length > 0) {
    // 非空目录直接失败：脚手架覆盖用户代码是不可接受的。
    // 空目录放行 —— `mkdir deps && cd deps && nofaultctl new x` 是很自然的用法。
    throw new Error(`directory already exists and is not empty: ${dir}`);
  }

  const files: string[] = [];
  const emit = (rel: string, content: string): void => {
    const abs = join(dir, rel);
    mkdirSync(pathDir(abs), { recursive: true });
    writeFileSync(abs, content, 'utf8');
    files.push(rel);
  };

  emit('package.json', packageJson(name));
  emit('tsconfig.json', tsconfig());
  emit('.gitignore', gitignore());
  emit('README.md', readme(name));
  emit('src/main.ts', mainTs(name));
  emit('src/app.module.ts', appModuleTs());
  emit(`api/${kebabCase(name)}.api.ts`, contractTs(name));

  log.step(`scaffolded ${files.length} file(s) into ${dir}`);
  return { dir, files };
}

function pathDir(abs: string): string {
  const i = abs.lastIndexOf('/');
  return i < 0 ? abs : abs.slice(0, i);
}

// --------------------------------------------------------------------- 模板

function packageJson(name: string): string {
  return `${JSON.stringify(
    {
      name: kebabCase(name),
      version: '0.1.0',
      private: true,
      description: `Generated by nofaultctl · ${new Date().toISOString().slice(0, 10)}`,
      scripts: {
        build: 'tsc -p tsconfig.json',
        start: 'node dist/main.js',
        dev: 'tsc -p tsconfig.json && node dist/main.js',
        generate: `nofaultctl generate api api/${kebabCase(name)}.api.ts --out src`,
      },
      dependencies: {
        '@nofault/core': '^0.4.0',
        '@nofault/rest': '^0.4.0',
        '@nofault/logger': '^0.4.0',
        'reflect-metadata': '^0.2.2',
      },
      devDependencies: {