// Code generated by nofaultctl. DO NOT EDIT.
import { Entity, Column, PrimaryGeneratedColumn } from '@nofault/orm';

@Entity({ table: 'ok_resp' })
export class OkResp {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ name: 'ok', type: 'string' })
  ok!: string;