// Code generated by nofaultctl. DO NOT EDIT.
import { Entity, Column, PrimaryGeneratedColumn } from '@nofault/orm';

@Entity({ table: 'user_resp' })
export class UserResp {
  @PrimaryGeneratedColumn()
  id!: number;
