// Code generated by nofaultctl. DO NOT EDIT.
import { Entity, Column, PrimaryGeneratedColumn } from '@nofault/orm';

@Entity({ table: 'user_page_resp' })
export class UserPageResp {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ name: 'total', type: 'int' })
  total!: number;

  @Column({ name: 'page', type: 'int' })
  page!: number;

}
