/**
 * 代码生成器：ApiSpec → 一组文件内容。
 *
 * 设计要点：
 * 1. **纯函数**：不写磁盘、不读全局状态，只做 spec → string 的变换。
 *    写盘单独放在 `writer.ts`，这样测试不需要临时目录，也可以做"dry run"。
 * 2. **契约驱动**：所有元信息来自 Spec，生成器不做业务猜测。
 * 3. **生成代码必须能编译**：这是硬要求，集成测试会真的 `tsc` 一遍。
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  FieldSource,
  type ApiSpec,
  type FieldSpec,
  type RouteSpec,
  type ServiceSpec,
  type TypeSpec,
} from '@nofault/dsl';
import { camelCase, kebabCase, pascalCase } from '@nofault/dsl';
import { renderTemplate } from './template';
import { DEFAULT_TEMPLATES } from './default-templates';

export type GeneratedKind =
  | 'dto'
  | 'service'
  | 'controller'
  | 'module'
  | 'app-module'
  | 'entity'
  | 'repository';

export interface GeneratedFile {
  /** 相对输出根目录的路径 */
  path: string;
  content: string;
  kind: GeneratedKind;
}

export interface TemplateOverrides {
  dto?: string;
  service?: string;
  controller?: string;
  module?: string;
  'app-module'?: string;
}

export interface GenerateOptions {
  /** 模板覆盖目录：存在 `<dir>/<name>.tpl` 就优先用它 */
  templatesDir?: string;
  /** 是否额外生成根 `app.module.ts` */
  rootModule?: boolean;
  /** 每个文件顶部的注释（用于打"此文件由生成器产生"的标记） */
  header?: string | false;
  /** 尚未支持的校验规则如何处理：`comment`（注释掉）或 `throw` */
  unknownRule?: 'comment' | 'throw';
}

export interface GenerateResult {
  files: GeneratedFile[];
  /** 生成过程中的非致命提示，例如"规则 X 不支持" */
  warnings: string[];
}

const METHOD_NO_BODY = new Set(['GET', 'HEAD', 'DELETE', 'OPTIONS']);

const RULE_TO_DECORATOR: Record<string, (rest: string) => { name: string; args: string[] } | undefined> = {
  isString: () => ({ name: 'IsString', args: [] }),
  isInt: () => ({ name: 'IsInt', args: [] }),
  isNumber: () => ({ name: 'IsNumber', args: [] }),
  isBoolean: () => ({ name: 'IsBoolean', args: [] }),
  isEmail: () => ({ name: 'IsEmail', args: [] }),
  isNotEmpty: () => ({ name: 'IsNotEmpty', args: [] }),
  minLength: (rest) => ({ name: 'MinLength', args: [rest] }),
  maxLength: (rest) => ({ name: 'MaxLength', args: [rest] }),
  min: (rest) => ({ name: 'Min', args: [rest] }),
  max: (rest) => ({ name: 'Max', args: [rest] }),
};

/** 只生成没有语法错的 TypeScript —— 规则值必须是字面量白名单，避免注入模板 */

function dtoFileName(typeName: string): string {
  return `${kebabCase(typeName)}.dto.ts`;
}

/**
 * 模块说明符（**不带** `.ts`）。
 *
 * ESM/TS 的 import 写的是模块名而不是文件名；把扩展名拼进去，
 * 在 `moduleResolution: bundler` 下直接编译不过。
 */
function dtoModulePath(typeName: string): string {
  return `./${kebabCase(typeName)}.dto`;
}

/**
 * 从 `<out>/<group>/` 引用 DTO 的相对路径。
 *
 * DTO 统一放在输出根目录的 `dto/` 下（**每个类型只有一份**，跨服务共享），
 * 而 controller/service 在 `<out>/<group>/` 里，所以要回退一级。
 * 早先写成 `./dto/...`，生成物编译直接失败——这个问题只有端到端编译才暴露得出来。
 */
function dtoModulePathFromService(typeName: string): string {
  return `../dto/${kebabCase(typeName)}.dto`;
}

export function generate(spec: ApiSpec, options: GenerateOptions = {}): GenerateResult {
  const warnings: string[] = [];
  const files: GeneratedFile[] = [];
  const templates = loadTemplates(options.templatesDir);
  const header =
    options.header === false
      ? ''
      : (options.header ?? `// Code generated by nofaultctl from ${spec.file ?? spec.name}. DO NOT EDIT.`);

  const typeNames = new Set(spec.types.map((t) => t.name));

  for (const type of spec.types) {
    files.push({
      kind: 'dto',
      path: `dto/${dtoFileName(type.name)}`,
      content: renderDto(type, typeNames, templates.dto, header, options, warnings),
    });
  }

  for (const service of spec.services) {
    const groupFiles = renderServiceFiles(service, spec, templates, header, options, warnings);
    files.push(...groupFiles);
  }

  if (options.rootModule && spec.services.length > 0) {
    const seen = new Set<string>();
    const modules: string[] = [];
    const imports: string[] = [];
    for (const service of spec.services) {
      const cls = `${pascalCase(service.group)}Module`;
      if (seen.has(cls)) continue;
      seen.add(cls);
      modules.push(cls);
      imports.push(`import { ${cls} } from './${kebabCase(service.group)}/${kebabCase(service.group)}.module';`);
    }
    files.push({
      kind: 'app-module',
      path: 'app.module.ts',
      content: renderTemplate(templates['app-module'] ?? DEFAULT_TEMPLATES['app-module']!, {
        header,
        imports: imports.join('\n'),
        modulesCsv: modules.join(', '),
        className: 'AppModule',
      }),
    });
  }

  return { files, warnings };
}

// --------------------------------------------------------------------- 各文件

function renderServiceFiles(
  service: ServiceSpec,
  spec: ApiSpec,
  templates: Record<string, string>,
  header: string,
  options: GenerateOptions,
  warnings: string[],
): GeneratedFile[] {
  const group = kebabCase(service.group || service.name);
  const className = pascalCase(service.group || service.name);
  const files: GeneratedFile[] = [];

  const types = new Map<string, TypeSpec>(spec.types.map((t) => [t.name, t]));
  const dtoImports = new Map<string, string>();

  // controller 侧会被 `@Param()` 逐个拆开绑定（看不到 DTO 类型），
  // service 侧的方法签名却要写 `req: XxxReq`（看得到）——两份清单因此不同。
  const controllerDtoImports = new Map<string, string>();

  const remember = (name: string, target: Map<string, string>): void => {
    target.set(name, `import { ${name} } from '${dtoModulePathFromService(name)}';`);
  };

  for (const route of service.routes) {
    if (route.requestType && !isBuiltinType(route.requestType)) {
      remember(route.requestType, dtoImports);
      const pathOnly = (types.get(route.requestType)?.fields ?? []).some(
        (f) => f.source === FieldSource.PATH,
      );
      if (!pathOnly) remember(route.requestType, controllerDtoImports);
    }
    if (route.responseType && !isBuiltinType(baseTypeOf(route.responseType))) {
      const name = baseTypeOf(route.responseType);
      remember(name, dtoImports);
      remember(name, controllerDtoImports);
    }
  }

  const methods = service.routes.map((route) => ({ body: renderServiceMethod(route, warnings) }));

  files.push({
    kind: 'service',
    path: `${group}/${kebabCase(className)}.service.ts`,
    content: renderTemplate(templates.service ?? DEFAULT_TEMPLATES.service!, {
      header,
      imports: [...dtoImports.values()].sort().join('\n'),
      className: `${className}Service`,
      methods,
    }),
  });

  files.push({
    kind: 'controller',
    path: `${group}/${kebabCase(className)}.controller.ts`,
    content: renderController(
      service,
      className,
      controllerDtoImports,
      types,
      templates,
      header,
      options,
    ),
  });

  files.push({
    kind: 'module',
    path: `${group}/${kebabCase(className)}.module.ts`,
    content: renderTemplate(templates.module ?? DEFAULT_TEMPLATES.module!, {
      header,
      imports: [
        `import { ${className}Controller } from './${kebabCase(className)}.controller';`,
        `import { ${className}Service } from './${kebabCase(className)}.service';`,
      ].join('\n'),
      className: `${className}Module`,
      controllersCsv: `${className}Controller`,
      providersCsv: `${className}Service`,
    }),
  });

  return files;
}

function renderController(
  service: ServiceSpec,
  className: string,
  dtoImports: Map<string, string>,
  types: Map<string, TypeSpec>,
  templates: Record<string, string>,
  header: string,
  _options: GenerateOptions,
): string {
  const routes = service.routes.map((route) => ({ body: renderRoute(route, types) }));

  const restSymbols = new Set<string>(['Controller']);
  for (const route of service.routes) {
    restSymbols.add(routeDecoratorFor(route.method));
    if (route.requestType) {
      const fields = types.get(route.requestType)?.fields ?? [];
      if (fields.some((f) => f.source === FieldSource.PATH)) {
        restSymbols.add('Param');
      } else {
        restSymbols.add(paramDecoratorFor(route));
        restSymbols.add('Validate');
      }
    }
  }
  if (service.routes.some((r) => (r.middleware ?? []).length > 0)) restSymbols.add('UseMiddleware');

  const imports = [
    `import { ${className}Service } from './${kebabCase(className)}.service';`,
    ...[...dtoImports.values()].sort(),
    `import { ${[...restSymbols].sort().join(', ')} } from '@nofault/rest';`,
  ].join('\n');

  const controllerPath = normalizePath(`${service.prefix ?? ''}/${service.group}`);
  const classDecorators: string[] = [];
  if (service.jwt) {
    classDecorators.push(`// 鉴权：${service.jwt}（框架 v0.4.0 尚未内建 JWT，此处留待接入）`);
  }

  return renderTemplate(templates.controller ?? DEFAULT_TEMPLATES.controller!, {
    header,
    imports,
    classDecorators: classDecorators.join('\n'),