/**
 * 代码生成器：ApiSpec → 一组文件内容。
 *
 * 设计要点：
 * 1. **纯函数**：不写磁盘、不读全局状态，只做 spec → string 的变换。
 *    写盘单独放在 `writer.ts`，这样测试不需要临时目录，也可以做"dry run"。
 * 2. **契约驱动**：所有元信息来自 Spec，生成器不做业务猜测。
 * 3. **生成代码必须能编译**：这是硬要求，集成测试会真的 `tsc` 一遍。
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  FieldSource,
  type ApiSpec,
  type FieldSpec,
  type RouteSpec,
  type ServiceSpec,
  type TypeSpec,
} from '@nofault/dsl';
import { camelCase, kebabCase, pascalCase } from '@nofault/dsl';
import { renderTemplate } from './template';
import { DEFAULT_TEMPLATES } from './default-templates';

export type GeneratedKind =
  | 'dto'
  | 'service'
  | 'controller'
  | 'module'
  | 'app-module'
  | 'entity'
  | 'repository';

export interface GeneratedFile {
  /** 相对输出根目录的路径 */
  path: string;
  content: string;
  kind: GeneratedKind;
}

export interface TemplateOverrides {
  dto?: string;
  service?: string;
  controller?: string;
  module?: string;
  'app-module'?: string;
}

export interface GenerateOptions {
  /** 模板覆盖目录：存在 `<dir>/<name>.tpl` 就优先用它 */
  templatesDir?: string;
  /** 是否额外生成根 `app.module.ts` */
  rootModule?: boolean;
  /** 每个文件顶部的注释（用于打"此文件由生成器产生"的标记） */
  header?: string | false;
  /** 尚未支持的校验规则如何处理：`comment`（注释掉）或 `throw` */
  unknownRule?: 'comment' | 'throw';
}

export interface GenerateResult {
  files: GeneratedFile[];
  /** 生成过程中的非致命提示，例如"规则 X 不支持" */
  warnings: string[];
}

const METHOD_NO_BODY = new Set(['GET', 'HEAD', 'DELETE', 'OPTIONS']);

const RULE_TO_DECORATOR: Record<string, (rest: string) => { name: string; args: string[] } | undefined> = {
  isString: () => ({ name: 'IsString', args: [] }),
  isInt: () => ({ name: 'IsInt', args: [] }),
  isNumber: () => ({ name: 'IsNumber', args: [] }),
  isBoolean: () => ({ name: 'IsBoolean', args: [] }),
  isEmail: () => ({ name: 'IsEmail', args: [] }),
  isNotEmpty: () => ({ name: 'IsNotEmpty', args: [] }),
  minLength: (rest) => ({ name: 'MinLength', args: [rest] }),
  maxLength: (rest) => ({ name: 'MaxLength', args: [rest] }),
  min: (rest) => ({ name: 'Min', args: [rest] }),
  max: (rest) => ({ name: 'Max', args: [rest] }),
};

/** 只生成没有语法错的 TypeScript —— 规则值必须是字面量白名单，避免注入模板 */

function dtoFileName(typeName: string): string {
  return `${kebabCase(typeName)}.dto.ts`;
}

/**
 * 模块说明符（**不带** `.ts`）。
 *
 * ESM/TS 的 import 写的是模块名而不是文件名；把扩展名拼进去，
 * 在 `moduleResolution: bundler` 下直接编译不过。
 */
function dtoModulePath(typeName: string): string {
  return `./${kebabCase(typeName)}.dto`;
}

/**
 * 从 `<out>/<group>/` 引用 DTO 的相对路径。
 *
 * DTO 统一放在输出根目录的 `dto/` 下（**每个类型只有一份**，跨服务共享），
 * 而 controller/service 在 `<out>/<group>/` 里，所以要回退一级。
 * 早先写成 `./dto/...`，生成物编译直接失败——这个问题只有端到端编译才暴露得出来。
 */
function dtoModulePathFromService(typeName: string): string {
  return `../dto/${kebabCase(typeName)}.dto`;
}

export function generate(spec: ApiSpec, options: GenerateOptions = {}): GenerateResult {
  const warnings: string[] = [];
  const files: GeneratedFile[] = [];
  const templates = loadTemplates(options.templatesDir);
  const header =
    options.header === false
      ? ''
      : (options.header ?? `// Code generated by nofaultctl from ${spec.file ?? spec.name}. DO NOT EDIT.`);

  const typeNames = new Set(spec.types.map((t) => t.name));

  for (const type of spec.types) {
    files.push({
      kind: 'dto',
      path: `dto/${dtoFileName(type.name)}`,
      content: renderDto(type, typeNames, templates.dto, header, options, warnings),
    });
  }

  for (const service of spec.services) {
    const groupFiles = renderServiceFiles(service, spec, templates, header, options, warnings);
    files.push(...groupFiles);
  }

  if (options.rootModule && spec.services.length > 0) {
    const seen = new Set<string>();
    const modules: string[] = [];
    const imports: string[] = [];
    for (const service of spec.services) {
      const cls = `${pascalCase(service.group)}Module`;
      if (seen.has(cls)) continue;
      seen.add(cls);
      modules.push(cls);
      imports.push(`import { ${cls} } from './${kebabCase(service.group)}/${kebabCase(service.group)}.module';`);
    }
    files.push({
      kind: 'app-module',
      path: 'app.module.ts',
      content: renderTemplate(templates['app-module'] ?? DEFAULT_TEMPLATES['app-module']!, {
        header,
        imports: imports.join('\n'),
        modulesCsv: modules.join(', '),
        className: 'AppModule',
      }),
    });
  }

  return { files, warnings };
}

// --------------------------------------------------------------------- 各文件

function renderServiceFiles(
  service: ServiceSpec,
  spec: ApiSpec,
  templates: Record<string, string>,
  header: string,
  options: GenerateOptions,
  warnings: string[],
): GeneratedFile[] {
  const group = kebabCase(service.group || service.name);
  const className = pascalCase(service.group || service.name);
  const files: GeneratedFile[] = [];

  const types = new Map<string, TypeSpec>(spec.types.map((t) => [t.name, t]));
  const dtoImports = new Map<string, string>();

  // controller 侧会被 `@Param()` 逐个拆开绑定（看不到 DTO 类型），
  // service 侧的方法签名却要写 `req: XxxReq`（看得到）——两份清单因此不同。
  const controllerDtoImports = new Map<string, string>();

  const remember = (name: string, target: Map<string, string>): void => {
    target.set(name, `import { ${name} } from '${dtoModulePathFromService(name)}';`);
  };

  for (const route of service.routes) {
    if (route.requestType && !isBuiltinType(route.requestType)) {
      remember(route.requestType, dtoImports);
      const pathOnly = (types.get(route.requestType)?.fields ?? []).some(
        (f) => f.source === FieldSource.PATH,
      );
      if (!pathOnly) remember(route.requestType, controllerDtoImports);
    }
    if (route.responseType && !isBuiltinType(baseTypeOf(route.responseType))) {
      const name = baseTypeOf(route.responseType);
      remember(name, dtoImports);
      remember(name, controllerDtoImports);
    }
  }

  const methods = service.routes.map((route) => ({ body: renderServiceMethod(route, warnings) }));

  files.push({
    kind: 'service',
    path: `${group}/${kebabCase(className)}.service.ts`,
    content: renderTemplate(templates.service ?? DEFAULT_TEMPLATES.service!, {
      header,
      imports: [...dtoImports.values()].sort().join('\n'),
      className: `${className}Service`,
      methods,
    }),
  });

  files.push({
    kind: 'controller',
    path: `${group}/${kebabCase(className)}.controller.ts`,
    content: renderController(
      service,
      className,
      controllerDtoImports,
      types,
      templates,
      header,
      options,
    ),
  });

  files.push({
    kind: 'module',
    path: `${group}/${kebabCase(className)}.module.ts`,
    content: renderTemplate(templates.module ?? DEFAULT_TEMPLATES.module!, {
      header,
      imports: [
        `import { ${className}Controller } from './${kebabCase(className)}.controller';`,
        `import { ${className}Service } from './${kebabCase(className)}.service';`,
      ].join('\n'),
      className: `${className}Module`,
      controllersCsv: `${className}Controller`,
      providersCsv: `${className}Service`,
    }),
  });

  return files;
}

function renderController(
  service: ServiceSpec,
  className: string,
  dtoImports: Map<string, string>,
  types: Map<string, TypeSpec>,
  templates: Record<string, string>,
  header: string,
  _options: GenerateOptions,
): string {
  const routes = service.routes.map((route) => ({ body: renderRoute(route, types) }));

  const restSymbols = new Set<string>(['Controller']);
  for (const route of service.routes) {
    restSymbols.add(routeDecoratorFor(route.method));
    if (route.requestType) {
      const fields = types.get(route.requestType)?.fields ?? [];
      if (fields.some((f) => f.source === FieldSource.PATH)) {
        restSymbols.add('Param');
      } else {
        restSymbols.add(paramDecoratorFor(route));
        restSymbols.add('Validate');
      }
    }
  }
  if (service.routes.some((r) => (r.middleware ?? []).length > 0)) restSymbols.add('UseMiddleware');

  const imports = [
    `import { ${className}Service } from './${kebabCase(className)}.service';`,
    ...[...dtoImports.values()].sort(),
    `import { ${[...restSymbols].sort().join(', ')} } from '@nofault/rest';`,
  ].join('\n');

  const controllerPath = normalizePath(`${service.prefix ?? ''}/${service.group}`);
  const classDecorators: string[] = [];
  if (service.jwt) {
    classDecorators.push(`// 鉴权：${service.jwt}（框架 v0.4.0 尚未内建 JWT，此处留待接入）`);
  }

  return renderTemplate(templates.controller ?? DEFAULT_TEMPLATES.controller!, {
    header,
    imports,
    classDecorators: classDecorators.join('\n'),
    path: controllerPath,
    middlewareCsv: service.middleware.map((m) => `'${m}'`).join(', '),
    className: `${className}Controller`,
    serviceClass: `${className}Service`,
    routes,
  });
}

function renderRoute(route: RouteSpec, types: Map<string, TypeSpec>): string {
  const lines: string[] = [];
  if (route.comment) lines.push(`  /** ${route.comment} */`);
  for (const mw of route.middleware ?? []) lines.push(`  @UseMiddleware('${mw}')`);
  if (route.requestType && needsValidationDecorator(route, types)) {
    lines.push(`  @Validate(${route.requestType})`);
  }
  lines.push(`  @${routeDecoratorFor(route.method)}('${route.path}')`);

  const { params, callArg } = callShape(route, types);
  lines.push(
    // 统一 async + Promise<…>：无响应时也必须写成 Promise<void>，
    // 否则 `return this.service.x()`（返回 Promise<void>）在 `: void` 签名下编译不过
    `  async ${camelCase(route.handler)}(${params}): Promise<${route.responseType ?? 'void'}> {\n` +
      `    return this.service.${camelCase(route.handler)}(${callArg});\n` +
      `  }\n`,
  );
  return `${lines.join('\n')}\n`;
}

/**
 * 决定 handler 的参数形态。
 *
 * 两种情形：
 * - 普通路由：整个请求体/查询串绑定到一个 DTO
 * - **带路径参数**的路由：`@Path` 字段必须用 `@Param()` 逐个接，
 *   剩下的字段仍绑到一个对象，最后在调用处展开合并。
 *   若不区分，`:id` 会跑去 query 里找，永远取不到值。
 */
function callShape(route: RouteSpec, types: Map<string, TypeSpec>): { params: string; callArg: string } {
  if (!route.requestType) return { params: '', callArg: '' };

  const fields = types.get(route.requestType)?.fields ?? [];
  const pathFields = fields.filter((f) => f.source === FieldSource.PATH);

  if (pathFields.length === 0) {
    const varName = camelCase(route.requestType);
    return {
      params: `@${paramDecoratorFor(route)}() ${varName}: ${route.requestType}`,
      callArg: varName,
    };
  }

  const parts: string[] = [];
  const spread: string[] = [];
  for (const f of pathFields) {
    const prop = camelCase(f.key || f.name);
    parts.push(`@Param('${f.key || f.name}') ${prop}: ${f.type}`);
    spread.push(prop);
  }
  if (fields.length > pathFields.length) {
    parts.push(`@Query() query: ${route.requestType}`);
    spread.unshift('...query');
  }
  return { params: parts.join(', '), callArg: `{ ${spread.join(', ')} }` };
}

/**
 * 参数装饰器选择。
 *
 * 规则：**GET/HEAD/DELETE/OPTIONS 一律走 Query**，即使契约里字段标了 body。
 * 原因有两个：GET 带 body 在多数网关和 CDN 上会被丢弃；
 * 而 `.api` DSL 里字段默认就是 body，直接映射会生成不可用的代码。
 */
function paramDecoratorFor(route: RouteSpec): string {
  return METHOD_NO_BODY.has(route.method.toUpperCase()) ? 'Query' : 'Body';
}

/**
 * 是否需要 `@Validate()`。
 *
 * 带**路径参数**的路由不加：它的字段是逐个 `@Param()` 接的，
 * 没有一个完整的"请求对象"可供整体校验，加上反而会把每个请求都判成缺字段。
 */
function needsValidationDecorator(route: RouteSpec, types: Map<string, TypeSpec>): boolean {
  if (!route.requestType) return false;
  const fields = types.get(route.requestType)?.fields ?? [];
  return !fields.some((f) => f.source === FieldSource.PATH);
}

function routeDecoratorFor(method: string): string {
  const upper = method.toUpperCase();
  return upper.charAt(0) + upper.slice(1).toLowerCase();
}

function renderServiceMethod(route: RouteSpec, warnings: string[]): string {
  void warnings;
  const ret = route.responseType ?? 'void';
  const arg = route.requestType ? `${camelCase(route.requestType)}: ${route.requestType}` : '';
  const lines: string[] = [];
  if (route.comment) lines.push(`  /** ${route.comment} */`);
  lines.push(
    `  async ${camelCase(route.handler)}(${arg}): Promise<${ret}> {\n` +
      `    throw new Error('not implemented: ${route.handler}');\n` +
      `  }\n`,
  );
  return `${lines.join('\n')}\n`;
}

function renderDto(
  type: TypeSpec,
  typeNames: Set<string>,
  template: string,
  header: string,
  options: GenerateOptions,
  warnings: string[],
): string {
  const validatorImports = new Set<string>();
  const crossImports = new Set<string>();

  const fields = type.fields.map((field) => {
    const decorators = renderFieldDecorators(field, validatorImports, options, warnings);
    if (!isBuiltinType(baseTypeOf(field.type)) && typeNames.has(baseTypeOf(field.type))) {
      const name = baseTypeOf(field.type);