// Code generated by nofaultctl from api/user.api.ts. DO NOT EDIT.
import { UserController } from './user.controller';
import { UserService } from './user.service';
import { Module } from '@nofault/core';

@Module({
  controllers: [UserController],
  providers: [UserService],
  exports: [UserService],
})
export class UserModule {}
