// Code generated by nofaultctl from api/user.api.ts. DO NOT EDIT.
import { UserService } from './user.service';
import { CreateUserReq } from '../dto/create-user-req.dto';
import { ListUsersReq } from '../dto/list-users-req.dto';
import { OkResp } from '../dto/ok-resp.dto';
import { UserPageResp } from '../dto/user-page-resp.dto';
import { UserResp } from '../dto/user-resp.dto';
import { Body, Controller, Delete, Get, Param, Post, Query, Validate } from '@nofault/rest';
@Controller({ path: '/api/user', middleware: ['RequestLogger'] })
export class UserController {
  constructor(private readonly service: UserService) {}