import { describe, expect, it } from 'vitest';
import { mkdtempSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { writeFiles } from '../src/writer';
import type { GeneratedFile } from '../src/generate';

const MARKER = 'Code generated by nofaultctl';

function file(path: string, content: string): GeneratedFile {
  return { path, content, kind: 'dto' };
}

function tmp(): string {
  return mkdtempSync(join(tmpdir(), 'codegen-'));
}

describe('writeFiles', () => {