import { describe, expect, it } from 'vitest';
import { mkdtempSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { writeFiles } from '../src/writer';
import type { GeneratedFile } from '../src/generate';

const MARKER = 'Code generated by nofaultctl';

function file(path: string, content: string): GeneratedFile {
  return { path, content, kind: 'dto' };
}

function tmp(): string {
  return mkdtempSync(join(tmpdir(), 'codegen-'));
}

describe('writeFiles', () => {
  it('creates missing files including nested directories', () => {
    const dir = tmp();
    const r = writeFiles([file('a/b/c.ts', 'x')], { outDir: dir });
    expect(r.written).toEqual(['a/b/c.ts']);
    expect(readFileSync(join(dir, 'a/b/c.ts'), 'utf8')).toBe('x');
  });

  it('skips identical files and does not report them as changed', () => {
    const dir = tmp();
    writeFiles([file('a.ts', 'same')], { outDir: dir });
    const r = writeFiles([file('a.ts', 'same')], { outDir: dir });
    expect(r.written).toHaveLength(0);
    expect(r.changed).toHaveLength(0);
    // 内容没变却出现在"变更列表"里，会让使用方以为要重新编译/重新提交
  });

  it('overwrites files it previously generated even without force', () => {