// Code generated by nofaultctl from api/user.api.ts. DO NOT EDIT.
import { IsEmail, IsInt, IsNotEmpty, IsOptional, IsString, Max, MaxLength, Min, MinLength } from '@nofault/rest';
export class CreateUserReq {
  @IsString()
  @IsNotEmpty()