// Code generated by nofaultctl from api/user.api.ts. DO NOT EDIT.
import { IsInt, Max, Min } from '@nofault/rest';
export class ListUsersReq {
  @IsInt()
  @Min(1)
  page!: number;
  @IsInt()
  @Min(1)
  @Max(100)
  pageSize!: number;
}
