// Code generated by nofaultctl from api/user.api.ts. DO NOT EDIT.
import { IsInt, IsOptional, IsString, MaxLength, MinLength } from '@nofault/rest';
export class UpdateUserReq {
  @IsInt()
  id!: number;
  @IsOptional()