// Code generated by nofaultctl. DO NOT EDIT.
import { Injectable } from '@nofault/core';
import { InjectRepository, Repository } from '@nofault/orm';
import { OkResp } from '../entities/ok-resp.entity';
