// Code generated by nofaultctl. DO NOT EDIT.
import { Injectable } from '@nofault/core';
import { InjectRepository, Repository } from '@nofault/orm';
import { UserPageResp } from '../entities/user-page-resp.entity';

@Injectable()
export class UserPageRespRepository {
  constructor(@InjectRepository(UserPageResp) private readonly repo: Repository<UserPageResp>) {}

  findById(id: number): Promise<UserPageResp | undefined> {
    return this.repo.findById(id);
  }

  /** 分页查询；业务需要的复杂条件请自己加方法 */
  paginate(page: number, pageSize: number) {
    return this.repo.paginate(page, pageSize);
  }

  async create(entity: UserPageResp): Promise<UserPageResp> {
    return this.repo.save(entity);
  }
}
