// Code generated by nofaultctl. DO NOT EDIT.
import { Injectable } from '@nofault/core';
import { InjectRepository, Repository } from '@nofault/orm';
import { UserPageResp } from '../entities/user-page-resp.entity';

@Injectable()
export class UserPageRespRepository {
  constructor(@InjectRepository(UserPageResp) private readonly repo: Repository<UserPageResp>) {}

  findById(id: number): Promise<UserPageResp | undefined> {
    return this.repo.findById(id);
  }